#!/usr/bin/env bash
set -e

while getopts ":u:w:p:" option;
do
  case $option in
  u)
    SSH_USER=$OPTARG
    ;;
  w)
    SSH_PASSWORD=$OPTARG
    ;;
  p)
    SSH_PORT=$OPTARG
    ;;
  :)
    echo "Option -$OPTARG needs an argument"
    ;;
  *)
    echo "Invalid optionn $OPTARG"
    ;;
  esac
done

if [ $SSH_USER ]; then
  useradd $SSH_USER
  usermod -aG wheel $SSH_USER

  if [ $SSH_PASSWORD ]; then
    echo -e "$SSH_PASSWORD\n$SSH_PASSWORD" | (passwd --stdin $SSH_USER)
  fi
else
  if [ $SSH_PASSWORD ]; then
    echo "ERROR: cannot set password without user"
  fi
fi

if [ $SSH_PORT ]; then
  sed -i "s/#Port 22/Port ${SSH_PORT}/g" /etc/ssh/sshd_config 
fi

exec /usr/sbin/sshd -D
